#!/bin/sh

binary_dir="bin"
bitcoin_dir="${HOME}/.bitcoin"
litecoin_dir="${HOME}/.litecoin"
btc_addr=modnSoevy3wuZoHCAEpqPjrXjjUb3qqwuw
ltc_addr=mujyVMutzD9RWe67eSq49XLMpoMKNthR32
wallet_path=${HOME}/.config/wallet/wallet.conf

ERROR_CODE=-1

sync_wallet () {
    WALLET_PASSWORD=12345678 bitmark-wallet -C "$wallet_path" btc -t sync
    WALLET_PASSWORD=12345678 bitmark-wallet -C "$wallet_path" ltc -t sync
}

# teminate bitcoind
while pgrep bitcoind >/dev/null
do
    bitcoin-cli stop
    sleep 2
done

# create default data directory
if [ ! -d "${bitcoin_dir}" ]; then
    printf "bitcoin directory not exist, creating...\n"
    mkdir "${bitcoin_dir}"
fi

# copy config file if not exist
if [ ! -f "${bitcoin_dir}/bitcoin.conf" ]; then
    printf "bitcoin config not exit...abort\n"
    exit $ERROR_CODE
fi

# remove existing regtest data directory
if [ -d "${bitcoin_dir}/regtest" ]; then
    printf "remove existing bitcoin regtest directory...\n"
    rm -r "${bitcoin_dir}/regtest"
fi

# start bitcoind
bitcoind -daemon
sleep 2

# make sure bitcoind is started
if pgrep bitcoind > /dev/null; then
    printf "\nbitcoind started...\n"
else
    printf "\nbitcoind not started...abort\n"
    exit $ERROR_CODE
fi

# terminate litecoind
while pgrep litecoind >/dev/null
do
    litecoin-cli stop
    sleep 2
done

# create default data directory
if [ ! -d "${litecoin_dir}" ]; then
    printf "litecoin directory not exist, creating...\n"
    mkdir "${litecoin_dir}"
fi

# copy config file if not exist
if [ ! -f "${litecoin_dir}/litecoin.conf" ]; then
    printf "litecoin config not exit...abort\n"
    exit $ERROR_CODE
fi

# remove existing regtest data directory
if [ -d "${litecoin_dir}/regtest" ]; then
    printf "remove existing litecoin regtest directory...\n"
    rm -r "${litecoin_dir}/regtest"
fi

# start litecoind
litecoind -daemon
sleep 2

# make sure litecoind is started
if pgrep litecoind > /dev/null; then
    printf "\nlitecoind started...\n"
else
    printf "\nlitecoind not started...abort\n"
    exit $ERROR_CODE
fi

sleep 5
sync_wallet

# mine for some coins
sleep 5
printf "generating coins..."
bitcoin-cli generatetoaddress 105 $btc_addr
litecoin-cli generatetoaddress 105 $ltc_addr

sync_wallet
