#!/bin/sh

recorderd_dir="${HOME}/.config/recorderd"
recorderd_file="recorderd.conf"

if pgrep recorderd >/dev/null; then
    printf "\nrecorderd is already started\n"
else
    while true;
    do
        if pgrep recorderd; then
            break
        fi

        cd "${recorderd_dir}"
        printf "starting recorderd..."
        nohup recorderd --config-file="${recorderd_file}" >/dev/null 2>&1 &

        # wait 5 seconds to check
        echo checking recroderd runing status...
        sleep 5
    done
    printf "recorderd start success\n"
fi
