#!/usr/local/bin/bash
set -e

conf_dir="conf"
bin_dir="${GOPATH}/bin"
config_dir="${HOME}/.config"
recorderd_dir="${config_dir}/recorderd"

ERROR_CODE=-1
SUCCESS_CODE=0

printf "\n"

# check if recorderd is built
if [ ! -f "${bin_dir}/recorderd" ]; then
    printf "recorderd build fail...\n"
    exit $ERROR_CODE
else
    printf "recorderd build success\n"
fi

# make sure recorderd config file exist
if [ -f "${recorderd_dir}/recorderd.conf" ]; then
    printf "recorder config file exist, do nothing...\n"
    exit 0
fi

# stop existing running recorderd
for pid in $(pgrep recorderd)
do
    printf "stop recorderd process %s...\n" "${pid}"
    pkill pid
done

# create data directory if not exist
if [ ! -d "${config_dir}" ] || [ ! -d "${config_dir}/recorderd" ]; then
    mkdir -p "${config_dir}/recorderd"
fi

# enter recorderd directory
cd "${recorderd_dir}"

# copy recorderd configuration if not exist
if [ ! -f "${recorderd_dir}/recorderd.conf" ]; then
    cp "${HOME}/${conf_dir}/recorderd.conf" "${recorderd_dir}/"
fi

# generate recorderd certificate if not exist
if [ ! -f "${recorderd_dir}/recorderd.public" ]; then
    recorderd --config-file=recorderd.conf generate-identity
fi

exit $SUCCESS_CODE
